### ISSUE TITLE
Ansible JSon object typecast

### ISSUE THREAD

**Issue by odumasFR** [mgeldert/pulse-vtm-ansible#2]
I wish to create several  virtual servers in the same task, using the 'with_items' construct.
For instance, in 
[basic_vserver.txt](https://github.com/mgeldert/pulse-vtm-ansible/files/1825435/basic_vserver.txt)

For jinja syntactic reasons, I MUST put quotes around the reference to the item.port variable, making it a string. Yet, when submitted, the REST API refuses the data since the 'port' attribute in the object has to be Uint.
Based on the PulseSecure REST API Reference, I modified the virtual_server.py to enforce the type of some attributes that I use before sending them to the REST, but I find it quite clumsy. Do you have any idea how to turn around that problem ?

**Comment by mgeldert** [comment]
Have you tried using `port: "{{ item.port | int }}"`?

**Comment by odumasFR** [comment]
Yes, i've tried it and it doesn't work. I guess it's because typecasting in string happens after the jinja evaluation of `{{item.port|int}}`

**Comment by odumasFR** [comment]
After some testing, it seems that the typecast problem is located in the AnsibleModule() function call, thus not related to this module. I'm closing the case.
